/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentapp;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class AddStudentIlFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentIlFrame
     */
    JTextField textField = new JTextField();

    public AddStudentIlFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Add Student");
        setVisible(false);

        KeyStroke enter = KeyStroke.getKeyStroke
        (KeyEvent.VK_ENTER, 0);
        InputMap map = jTable1.getInputMap
        (jTable1.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );
        map.put(enter, "selectNextColumnCell");
        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Name", "Place", "Age"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterKeyPressed
        // TODO add your handling code here:
        int t_row_count = jTable1.getRowCount();
        int t_column_count = jTable1.getColumnCount();
        int t_selected_count = jTable1.getSelectedRow();
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        System.out.println(t_row_count);
        System.out.println(row);
        System.out.println(col);
        System.out.println(t_selected_count);
        System.out.println(jTable1.getEditingColumn());
        System.out.println("**************************************************");
        int key = evt.getKeyCode();
//        jtable_calc();
        if (key == KeyEvent.VK_ENTER) {
//            jTable1.requestFocusInWindow();
//            add_tab_row();
//            if (jTable1.getEditingColumn() == col) {
//                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//                tableModel.addRow(new Object[]{"", "", "", ""});
//            }
            if (col == -1) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(new Object[]{"", "", "", ""});
            }

            if (col == t_column_count - 1
                    && row == t_row_count
                    - 1) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(new Object[]{"", "", "", ""});
//                jTable1.setColumnSelectionInterval(0, 0);
            }
        }
    }//GEN-LAST:event_EnterKeyPressed

    void jtable_calc() {
        textField.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "selectNextColumnCell");
        textField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                int key = evt.getKeyCode();
                if (textField.getText().length() != 0) {
                    int row1 = jTable1.getSelectedRow(), col = jTable1.getEditingColumn();
                }
            }

            @Override
            public void keyPressed(KeyEvent evt) {
                String val = "";
                int col = jTable1.getSelectedColumn();
                int t_row_count = jTable1.getRowCount();
                int t_selected_count = jTable1.getSelectedRow() + 1;
                int key = evt.getKeyCode();
                int row = jTable1.getSelectedRow();
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (col == 1) {
//                            jTable1.getSelectedRow(), 3, false, false
                        jTable1.changeSelection(jTable1.getSelectedRow(), 1, false, false);
                        jTable1.getEditorComponent().requestFocus();
                    }
                }
            }
//            public void keyReleased(java.awt.event.KeyEvent evt) 
        });
//        DefaultCellEditor DefaultCellEditorV = new DefaultCellEditor(qty_clc);
//        jTable1.getColumnModel().getColumn(1).setCellEditor(DefaultCellEditorV);
//        jTable1.getColumnModel().getColumn(2).setCellEditor(DefaultCellEditorV);
//        jTable1.getColumnModel().getColumn(3).setCellEditor(DefaultCellEditorV);
//        jTable1.getColumnModel().getColumn(4).setCellEditor(DefaultCellEditorV);
    }

    void add_tab_row() {
        int row = jTable1.getRowCount(), row1 = jTable1.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.addRow(new Object[]{jTable1.getRowCount() + 1, "", "", ""});
        jTable1.requestFocus();
        jTable1.changeSelection(-1, -1, false, false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
